### ISSUE TITLE
A question for '/pathto/bart-large' is not found

### ISSUE THREAD

**Issue by 14H034160212** [zzshou/amr-data-augmentation#1]
Hi,

I got an issue when I replicate this project and I met the model not found issue. Does the model not been available now?
![image](https://user-images.githubusercontent.com/23516191/221471180-3ce73a26-989a-49c7-be2c-1ea7fa509f29.png)

Kind regards,
Qiming

**Comment by zzshou** [comment]
Hi Qiming,

We adopted AMR generators from paper "Investigating Pretrained Language Models for Graph-to-Text Generation”. You can find checkpoints from https://github.com/UKPLab/plms-graph2text.

Ziyi

**Comment by 14H034160212** [comment]
Thanks Ziyi.
